# Warnings currently triggered by your code
- ignore: {name: "Avoid lambda"} # 1 hint
- ignore: {name: "Avoid lambda using `infix`"} # 1 hint
- ignore: {name: "Eta reduce"} # 9 hints
- ignore: {name: "Functor law"} # 1 hint
- ignore: {name: "Move brackets to avoid $"} # 3 hints
- ignore: {name: "Redundant $"} # 4 hints
- ignore: {name: "Redundant <$>"} # 5 hints
- ignore: {name: "Redundant bracket"} # 44 hints
- ignore: {name: "Redundant case"} # 5 hints
- ignore: {name: "Redundant id"} # 1 hint
- ignore: {name: "Redundant return"} # 1 hint
- ignore: {name: "Unused LANGUAGE pragma"} # 1 hint
- ignore: {name: "Use $>"} # 28 hints
- ignore: {name: "Use <$>"} # 1 hint
- ignore: {name: "Use camelCase"} # 41 hints
- ignore: {name: "Use concatMap"} # 2 hints
- ignore: {name: "Use fmap"} # 2 hints
- ignore: {name: "Use guards"} # 3 hints
- ignore: {name: "Use infix"} # 1 hint
- ignore: {name: "Use isJust"} # 1 hint
- ignore: {name: "Use isNothing"} # 3 hints
- ignore: {name: "Use newtype instead of data"} # 2 hints
- ignore: {name: "Use notElem"} # 2 hints
- ignore: {name: "Use when"} # 1 hint

# Specify additional command line arguments
- arguments:
    - --ignore-glob=compiler/src/Language/Bond/Codegen/Cpp/Types_h.hs
